# Generated by Django 4.2.7 on 2025-06-05 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roadmaps', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roadmap',
            name='is_public',
        ),
        migrations.AddField(
            model_name='roadmap',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
