# Generated by Django 4.2.7 on 2025-06-07 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roadmaps', '0002_remove_roadmap_is_public_roadmap_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='roadmap',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='roadmapnode',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
