# Generated by Django 4.2.7 on 2025-06-07 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('roadmaps', '0003_roadmap_is_public_roadmapnode_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roadmap',
            name='is_public',
        ),
    ]
